server:
    port: ${MUL_PORT}

spring:
    application:
        name: mulberrydoc-${MUL_NAME}
    cloud:
        gateway:
            discovery:
                locator:
                    enable: true
                    lower-case-service-id: true
            routes:
                -   id: consumer_route
                    uri: lb://mulberrydoc-mul-consumer
                    #                    uri: lb://my-load-balanced-service
                    predicates:
                        - Path=/api/**
                    filters:
                        - StripPrefix=1

#ribbon:
#    eureka:
#        enabled: false
#    NFLoadBalancerRuleClassName: com.cqwu.jwy.mulberrydoc.gateway.ribbon.MyRoundRule
#    NFLoadBalancerPingClassName: com.cqwu.jwy.mulberrydoc.gateway.ribbon.HealthExamination
#
#my-load-balanced-service:
#    ribbon:
#        listOfServers: localhost:11001,localhost:11002
#        NFLoadBalancerRuleClassName: com.cqwu.jwy.mulberrydoc.gateway.ribbon.MyRoundRule
#        NFLoadBalancerPingClassName: com.cqwu.jwy.mulberrydoc.gateway.ribbon.HealthExamination

eureka:
    instance:
        instance-id: ${MUL_NAME}-${MUL_PORT}
        prefer-ip-address: true
        #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然活着，默认30秒
        lease-renewal-interval-in-seconds: 10
        #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实例删除
        lease-expiration-duration-in-seconds: 10
    client:
        #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
        registry-fetch-interval-seconds: 10
        service-url:
            register-with-eureka: true
            fetch-registry: true
            defaultZone: ${MUL_DEFAULTZONE}
